spring.datasource.url=jdbc:postgresql://localhost:5432/parking_db?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.data.redis.repositories.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration,org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration

logging.level.root=INFO
logging.level.parking_Building_Management_System=DEBUG
logging.level.org.springframework=INFO

app.jwt.secret=dev_secret_key_change_in_production

server.port=8080

# VNPay Sandbox Configuration
vnpay.tmn-code=EXOAVBEN
vnpay.hash-secret=Z2Z098TFC9K7UP41UG3DNZURG5HAPX0H
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/payment/vnpay-return
vnpay.version=2.1.0
vnpay.command=pay